/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Swing;

import Models.Operations;
import Models.Post;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;

/**
 *
 * @author Rehman Butt
 */
public class News_Feed extends javax.swing.JFrame {

    /**
     * Creates new form News_Feed
     *
     */

    public News_Feed() {
        initComponents();
    }
    public static BufferedImage scaleImage(int w, int h, BufferedImage img) throws Exception {
        BufferedImage bi;
        bi = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = bi.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(img, 0, 0, w, h, null);
        g2d.dispose();
        return bi;
    }
    /*News_Feed(ArrayList<String> location) {

        initComponents();

        for(int i=0;i<location.size();i++)
        {
            addpic(location.get(i));
        }
    }*/

    News_Feed(ArrayList<Post> feedPosts , Operations BLOp) throws Exception {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComponents();
        for(int i=0;i< feedPosts.size();i++)
        {
            addpic(feedPosts.get(i).imagePath);
        }

    }

    public void addpic(String location) throws Exception {
        BufferedImage image = null;
        URL url = null;
        try {
            url = new URL("file:" + location);
        } catch (MalformedURLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        image = ImageIO.read(url);;
        //String convertedPicLocation="C:\\Users\\Rehman Butt\\Desktop\\p2.png";
        JLabel label= new JLabel(new ImageIcon(scaleImage(170, 180, image)));;
        //JLabel label = new JLabel(icon);
        label.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));


        JButton like = new JButton("Like");
        like.addActionListener( likeAction ->
        {
            //to implement like button
        });
        like.setBounds(1,1,1,1);


        JButton removePost = new JButton("Remove Following Post");
        like.addActionListener( removeAction ->
        {
            //to implement like button
        });


        JButton viewComments = new JButton("View Comments");
        like.addActionListener( viewCommentsAction ->
        {
            //to implement like button
        });

        //like.setAlignmentX(TOP_ALIGNMENT);

        JButton share = new JButton("Share");
        JButton comment = new JButton("Comment");
        JTextArea commentText =new JTextArea();
        commentText.setWrapStyleWord(true);
        setBounds(100, 100, 565, 390);

        //jPanel1.setBounds(100, 100, 565, 390);

        JLabel test = new JLabel("this is another pannel to make buttons in flow layout");

        jPanel1.add(removePost);
        jPanel1.add(label);
        jPanel1.add(like);
        jPanel1.add(share);
        jPanel1.add(comment);
        jPanel1.add(commentText);
        jPanel1.add(viewComments);

        jPanelDesc=new JPanel();
        jPanelDesc.add(test);

        jPanel1.add(jPanelDesc);

        setVisible(true);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FEED");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel1)
                                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(273, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;                 // feed on the top of frame
    private javax.swing.JPanel jPanel1;                 // Child of below jScrollPanel1
    private javax.swing.JScrollPane jScrollPane1;       // child of this main JFrame
    private javax.swing.JPanel jPanelDesc;
    // End of variables declaration
}
